mod footer;
mod github_link;
mod grid_background;
mod hero;
mod home;
mod install_cmd;
mod nav_menu;
mod releases;
mod stats;
mod version;
mod x_link;

pub use footer::Footer;
pub use github_link::GithubLink;
pub use grid_background::GridBackground;
pub use hero::Hero;
pub use home::Home;
pub use install_cmd::InstallCmd;
pub use nav_menu::NavMenu;
pub use releases::Releases;
pub use stats::Stats;
pub use version::Version;
pub use x_link::XLink;
